### ISSUE TITLE
Error bad status: 429 It stopped working

### ISSUE THREAD

**Issue by milindmore22** [wpdirectory/wpdir#37]
It's stopped working
you can check the recent searches are not updated as well which was showing a recent search.

![image](https://user-images.githubusercontent.com/1132541/117158147-cab1ea80-addc-11eb-8bd2-4b9428aa953e.png)

**Comment by PeterBooker** [comment]
Thank you so much for letting me know @milindmore22 , it needed a restart. Some API calls were still working, including the health status endpoint used so the monitoring did not catch it. I have added a rule to the monitoring to check if no searches are made in a day, so hopefully I will catch this earlier.

I appreciate you letting me know, it looks like it is working now but it was down for around a week.

(edit: As for what was wrong there is nothing in the error log so I suspect it might have gotten stuck with the mutex lock for each repository (plugins, themes) locked. I am not sure how that could happen though.)

**Comment by milindmore22** [comment]
Sorry for making an issue here, Thanks for your prompt action,  yes the issue seems to be fixed.
I didn't know where to report it, please close the issue if not needed anymore

**Comment by PeterBooker** [comment]
Here was a perfect place to let me know, thanks again.
